# Generated by Django 4.2.7 on 2024-02-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.doctor')),
                ('regid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescdate', models.DateField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=100)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paydate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.booking')),
            ],
        ),
    ]
