# Generated by Django 4.2.7 on 2024-02-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0002_booking_prescription_payment_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='bid',
        ),
    ]
