# Generated by Django 4.2.7 on 2024-02-18 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0003_remove_medicine_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescdate',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription',
        ),
        migrations.AddField(
            model_name='booking',
            name='bookeddate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='rate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PresMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, null=True)),
                ('qty', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.prescription')),
            ],
        ),
    ]
