# Generated by Django 4.2.7 on 2024-02-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0005_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
