# Generated by Django 4.2.7 on 2024-02-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0006_booking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
