# Generated by Django 4.2.7 on 2024-02-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0007_medicine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='status',
            field=models.CharField(default='Available', max_length=10, null=True),
        ),
    ]
