# Generated by Django 4.2.7 on 2024-02-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0008_alter_medicine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='presmedicine',
            name='status',
            field=models.CharField(default='Prescribed', max_length=10, null=True),
        ),
    ]
